# Generated by Django 5.2.4 on 2025-07-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
