# Generated by Django 5.2.4 on 2025-07-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_data_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
