# Generated by Django 5.2.4 on 2025-07-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_usersocialauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='country_images/'),
        ),
    ]
