# Generated by Django 4.0.6 on 2025-07-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_data_options_alter_data_country_and_more'),
    ]

    operations = [
    ]
