# Generated by Django 4.0.6 on 2025-07-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_populate_defaults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Données géographiques'},
        ),
        migrations.AddField(
            model_name='data',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
