# Generated by Django 5.2.4 on 2025-07-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_userposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposition',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='position_photos/'),
        ),
    ]
