# Generated by Django 5.2.4 on 2025-07-26 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_userposition_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AlterModelOptions(
            name='userposition',
            options={'verbose_name': 'Position utilisateur', 'verbose_name_plural': 'Positions utilisateurs'},
        ),
        migrations.RenameField(
            model_name='userdrawnpolygon',
            old_name='coordinates',
            new_name='geo_json',
        ),
        migrations.AddField(
            model_name='userdrawnpolygon',
            name='countries_included',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdrawnpolygon',
            name='population_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userposition',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='position_photos/', verbose_name='Photo'),
        ),
        migrations.DeleteModel(
            name='UserSocialAuth',
        ),
    ]
