"""
Django settings for heatmap project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Chemins par défaut pour Windows
if os.name == 'nt':
    # Option 1: Chemins Conda (prioritaire)
    conda_gdal_path = r'C:\Users\ASUS\miniconda3\envs\gis_env\Library\bin\gdal304.dll'
    conda_geos_path = r'C:\Users\ASUS\miniconda3\envs\gis_env\Library\bin\geos_c.dll'

    # Option 2: Chemins OSGeo4W (fallback)
    osgeo_gdal_path = r'C:\OSGeo4W\bin\gdal304.dll'
    osgeo_geos_path = r'C:\OSGeo4W\bin\geos_c.dll'

    # Configuration automatique
    if Path(conda_gdal_path).exists():
        GDAL_LIBRARY_PATH = conda_gdal_path
        GEOS_LIBRARY_PATH = conda_geos_path
        os.environ['PATH'] = f"{os.path.dirname(conda_gdal_path)};{os.environ['PATH']}"
    elif Path(osgeo_gdal_path).exists():
        GDAL_LIBRARY_PATH = osgeo_gdal_path
        GEOS_LIBRARY_PATH = osgeo_geos_path
        os.environ['PATH'] = f"C:\\OSGeo4W\\bin;{os.environ['PATH']}"  # Ou utilisez une raw string
    else:
        GDAL_LIBRARY_PATH = None
        GEOS_LIBRARY_PATH = None


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bj8qo4)m63y=1^5ti8!1+p=3qfrl(@4yd&-&$m=#)3tb*oxha#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (20.0, 0.0),
    'DEFAULT_ZOOM': 2,
    'SCALE': 'both',
    'ATTRIBUTION_PREFIX': 'Cartographie Django',
}
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',  # Doit précéder contenttypes
    'django.contrib.contenttypes',  # UNE SEULE FOIS
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard.apps.DashboardConfig',  # Référence complète
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'heatmap.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'heatmap.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Utilisez SQLite standard
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
